default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: flack_development

test:
  <<: *default
  database: flack_test

production:
  <<: *default
  database: flack_production
  username: <%= ENV['FLACK_DATABASE_USERNAME'] %>
  password: <%= ENV['FLACK_DATABASE_PASSWORD'] %>
